<?php

return [
    'validation' => [
        'attachments' => [
            'extensions' => [
                'md',
                'markdown',
                'txt',
                'sh',
                'bash',
                'zsh',
                'py',
                'rb',
                'php',
                'js',
                'mjs',
                'cjs',
                'ts',
                'tsx',
                'jsx',
                'vue',
                'go',
                'rs',
                'java',
                'kt',
                'swift',
                'c',
                'cc',
                'cpp',
                'h',
                'hpp',
                'cs',
                'sql',
                'json',
                'yaml',
                'yml',
                'toml',
                'xml',
                'csv',
                'ini',
                'env',
                'conf',
                'config',
                'log',
                'html',
                'css',
                'scss',
                'sass',
                'less',
            ],
        ],
    ],
    'classification' => [
        'text' => [
            'mime_types' => [
                'text/markdown',
                'text/x-markdown',
                'application/x-markdown',
                'text/plain',
                'application/x-sh',
                'application/x-shellscript',
                'application/json',
                'application/xml',
                'text/xml',
                'application/x-yaml',
                'text/yaml',
                'text/x-python',
                'application/x-python-code',
                'text/x-php',
                'application/x-httpd-php',
                'text/javascript',
                'application/javascript',
                'text/csv',
                'text/html',
                'text/css',
                'text/x-sql',
            ],
        ],
        'images' => [
            'mime_types' => ['image/jpeg', 'image/png', 'image/webp', 'image/gif'],
            'extensions' => ['jpg', 'jpeg', 'png', 'webp', 'gif'],
        ],
    ],
];
